services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: vano
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: weather_db
    ports:
      - '5441:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_PORT: 5441
      DB_USERNAME: vano
      DB_PASSWORD: password123
      DB_NAME: weather_db
      JWT_SECRET: B[T@_6_-M2ux\^u),<7D9hsu99x.2-}bX_2bUXgnW?#5YT*cn$d{HjvBW^#Jfs]j
      JWT_EXPIRATION: 3600s
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:
